### ISSUE TITLE
Is support for SHA-256 and Blake-3 right?

### ISSUE THREAD

**Issue by darobin** [darobin/dasl.ing#1]
Blake-3 is very useful for streaming verification of large files, but at the same time it's not supported in the browser, which makes it heavy to include.

**Comment by bnewbold** [comment]
FWIW, for atproto we are a bit split on it. on the one hand we'd like to use it for larger media files (videos) at some point. on the other hand, it tends to have performance-sensitive implementation and ends up pulling in deps and longer builds, even in non-Javascript languages. so being able to not use it until we actually need it would be nice.

(this is my informal take, not an official/formal bsky team consensus)

**Comment by darobin** [comment]
That's good to hear because I think it reflects conversations happening elsewhere. I'm sort of landing on "we support B3 but implementations should default to SHA and people shouldn't use it unless they have a good reason." It's ungainly, but then again `this_is_standards.gif`.

**Comment by bumblefudge** [comment]
SHA2-256 or SHA3-256? something something length-extension attacks (in the case of the former).  see also:

https://github.com/w3c/webcrypto/issues/319#issuecomment-2302631189

**Comment by mishmosh** [comment]
> we support B3 but implementations should default to SHA

I think it's worth being very explicit about this for tooling, e.g.:
- MUST default to SHA
- MUST support B3 by flag (if B3 ends up blessed in DASL, given size/ browser concerns)

**Comment by achingbrain** [comment]
This is worth following along with - https://github.com/w3c/webcrypto/issues/73 - it seems that things are moving towards supporting streams in Web Crypto so we'll be able to use SHA-256 to hash arbitrary streams of data without needing any extra dependencies.

The addition of Blake-3 seems unlikely without people like us pushing for it and even then getting all the relevant parties on board will be difficult and  the timescales are likely to be glacial, given the years it's taken to move Ed25519 along.
