### ISSUE TITLE
Tighten CID parsing

### ISSUE THREAD

**Issue by DavidBuchanan314** [darobin/dasl.ing#5]
The steps currently documented are:

1. Accept an array of bytes CID bytes.
2. Remove the first byte in CID bytes and store it in version.
3. If version is not equal to 1, throw an error.
4. Remove the next byte in CID bytes and store it in codec.
5. If codec is not equal to 0x55 (raw) or 0x71 (dCBOR42), throw an error.
6. Remove the next two bytes in CID bytes and store them in hash type and hash size, respectively.
7. If hash type is not equal to 0x12 (SJA-256) or 0x1e (Blake-3), throw an error.
8. Store the rest of CID bytes in digest.
9. Return version, codec, hash type, hash size, and digest

Should there be a check that "the rest of the CID bytes" is actually equal in length to the declared hash size?

PS, I assume SJA-256 is a typo ;)

**Comment by bumblefudge** [comment]
(I caught SJA in my PR)

**Comment by darobin** [comment]
Good point! In 3a58007 I've applied a different fix: it'll throw if you don't have enough bytes left, otherwise it takes the right number for the digest and also returns remaining bytes. That way you could have that with some trailing bytes and get them back.

Not necessarily married to this, but we have a length, might as well use it.

**Comment by DavidBuchanan314** [comment]
Hm, such a definition would not play too nicely with how CIDs are used in CAR.

In CAR (v1, I think?), the CID and its corresponding data value are concatenated with each other. To extract the data portion, you first have to parse the CID in its entirety to determine its length. (I'm not fond of this aspect of CAR, which I've written more about here: https://github.com/ipld/ipld/issues/319 )

If you tried to store your CID-with-trailing-bytes in a CAR, you'd get an invalid CAR file.

Also, ideally, if you have valid DASL data, it's automatically valid IPLD data (and you can process it with existing IPLD tooling). I suspect a lot of existing IPLD tooling would barf on over-long CIDs - although I haven't checked!

**Comment by bumblefudge** [comment]
trailing bytes bad-- i'm with retr0id on this one

**Comment by bumblefudge** [comment]
I feel dirty typing this out, BUT theoretically a CARv2 (or CARv2.1 or CARv3, this might require adding "additional characteristics" to the CARv2 format) _could_ contain all the trailing-bit versions of those CIDs and ALSO include the no-trailing-bit versions of the same CIDs [inside the backwards-compatible CARv1 payload](https://ipld.io/specs/transport/car/carv2/#carv1-data-payload). <walks off cackling maniacally>

(for the record I still prefer disallowing trailing bits, feels like "bad CBOR", just pointing out how chaotic the current CARv1/v2 landscape is and how much room there is to respecify CARv2 if needed to patch these corner cases)

**Comment by darobin** [comment]
Ok! I honestly don't have strong feelings either way. I've removed the possibility to trail.
